// ═══ PDD — Provisão para Devedores Duvidosos (CPC 48 / IFRS 9) ═══

// ── Interfaces ──

export interface AgingBucket {
  range: string;
  daysFrom: number;
  daysTo: number | null;
  pdPercent: number;
  stage: 1 | 2 | 3;
  lgdPercent: number;
  color: string;
}

export interface PddDebtor {
  id: string;
  name: string;
  cnpj: string;
  segment: "corporate" | "mid_market" | "small_business";
  totalExposure: number;
  daysOverdue: number;
  oldestDueDate: string;
  internalRating: "AAA" | "AA" | "A" | "BBB" | "BB" | "B" | "CCC" | "D";
  ratingPreviousMonth: "AAA" | "AA" | "A" | "BBB" | "BB" | "B" | "CCC" | "D";
  hasCollateral: boolean;
  collateralValue: number;
  isRestructured: boolean;
  isOnWatchlist: boolean;
  recentNegativeEvents: string[];
  stage: 1 | 2 | 3;
  pdPercent: number;
  lgdPercent: number;
  ead: number;
  ecl: number;
  pddRequired: number;
  sicr: boolean;
  sicrReasons: string[];
  earlyWarningScore: number;
  earlyWarningSignals: string[];
}

export interface PddParameter {
  id: string;
  bucketRange: string;
  stage: 1 | 2 | 3;
  pdPercent: number;
  lgdPercent: number;
  basis: "CPC48" | "IFRS9" | "Custom";
  lastUpdated: string;
  updatedBy: string;
  justification: string;
}

export interface PddClosing {
  id: string;
  referenceMonth: string;
  closingDate: string;
  status: "open" | "pending_approval" | "approved" | "posted";
  approvedBy: string | null;
  totalEAD: number;
  totalECL: number;
  totalPddBalance: number;
  totalPddPreviousMonth: number;
  movementConstitution: number;
  movementReversal: number;
  movementWriteOff: number;
  movementRecovery: number;
  netMovement: number;
  journalEntryId: string | null;
  stage1EAD: number; stage1ECL: number;
  stage2EAD: number; stage2ECL: number;
  stage3EAD: number; stage3ECL: number;
  coverageRatio: number;
  nplRatio: number;
}

export interface PddHistory {
  month: string;
  referenceDate: string;
  totalEAD: number;
  totalPdd: number;
  coverageRatio: number;
  stage1Pdd: number;
  stage2Pdd: number;
  stage3Pdd: number;
  nplRatio: number;
  costOfCredit: number;
}

export interface PddJournalEntry {
  id: string;
  date: string;
  referenceMonth: string;
  type: "constitution" | "reversal" | "write_off" | "recovery";
  description: string;
  debitAccount: string;
  debitAccountName: string;
  creditAccount: string;
  creditAccountName: string;
  amount: number;
  status: "auto_generated" | "posted" | "reversed";
  autoGenerated: boolean;
  generatedBy: string;
  approvedBy: string | null;
  closingId: string;
}

export interface PddOverride {
  id: string;
  debtorId: string;
  debtorName: string;
  field: "stage" | "pdPercent" | "lgdPercent" | "ead";
  originalValue: number | string;
  overrideValue: number | string;
  justification: string;
  requestedBy: string;
  approvedBy: string | null;
  date: string;
  status: "pending" | "approved" | "rejected";
}

export interface MacroScenario {
  id: string;
  name: string;
  probability: number;
  gdpGrowth: number;
  interestRate: number;
  unemployment: number;
  inflation: number;
  pdMultiplier: number;
  lgdMultiplier: number;
  expectedPddImpact: number;
  color: string;
}

// ── Aging Buckets ──

export const agingBuckets: AgingBucket[] = [
  { range: "Corrente (0d)", daysFrom: 0, daysTo: 0, pdPercent: 0.01, stage: 1, lgdPercent: 0.30, color: "hsl(142,76%,36%)" },
  { range: "1-30 dias", daysFrom: 1, daysTo: 30, pdPercent: 0.03, stage: 1, lgdPercent: 0.35, color: "hsl(45,100%,50%)" },
  { range: "31-60 dias", daysFrom: 31, daysTo: 60, pdPercent: 0.20, stage: 2, lgdPercent: 0.50, color: "hsl(25,100%,50%)" },
  { range: "61-90 dias", daysFrom: 61, daysTo: 90, pdPercent: 0.50, stage: 2, lgdPercent: 0.65, color: "hsl(354,100%,64%)" },
  { range: "+90 dias", daysFrom: 91, daysTo: null, pdPercent: 1.00, stage: 3, lgdPercent: 0.80, color: "hsl(252,100%,69%)" },
];

// ── Debtors ──

export const pddDebtors: PddDebtor[] = [
  {
    id: "PDD-001", name: "Omega Corp", cnpj: "98.765.432/0001-01",
    segment: "corporate", totalExposure: 248000, daysOverdue: 114, oldestDueDate: "2024-11-15",
    internalRating: "D", ratingPreviousMonth: "CCC",
    hasCollateral: true, collateralValue: 180000, isRestructured: false, isOnWatchlist: true,
    recentNegativeEvents: ["Protesto registrado em cartório", "Pedido de recuperação judicial em análise"],
    stage: 3, pdPercent: 1.00, lgdPercent: 0.65, // reduced from 0.80 due to collateral
    ead: 248000, ecl: 248000 * 1.00 * 0.65, pddRequired: 248000 * 1.00 * 0.65,
    sicr: true, sicrReasons: ["Atraso > 90 dias", "Downgrade de rating D", "Evento negativo: protesto"],
    earlyWarningScore: 92, earlyWarningSignals: ["Deterioração contínua de rating", "Protestos em cartório", "Pedido de RJ"],
  },
  {
    id: "PDD-002", name: "Delta Sys", cnpj: "12.876.543/0001-02",
    segment: "mid_market", totalExposure: 195000, daysOverdue: 79, oldestDueDate: "2024-12-20",
    internalRating: "CCC", ratingPreviousMonth: "B",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: true,
    recentNegativeEvents: ["Queda de 40% no faturamento reportado"],
    stage: 2, pdPercent: 0.50, lgdPercent: 0.65,
    ead: 195000, ecl: 195000 * 0.50 * 0.65, pddRequired: 195000 * 0.50 * 0.65,
    sicr: true, sicrReasons: ["Atraso 61-90 dias", "Downgrade de rating de B para CCC"],
    earlyWarningScore: 72, earlyWarningSignals: ["Queda significativa de faturamento", "Downgrade de rating"],
  },
  {
    id: "PDD-003", name: "Kappa Serviços", cnpj: "45.678.912/0001-03",
    segment: "mid_market", totalExposure: 156000, daysOverdue: 63, oldestDueDate: "2025-01-05",
    internalRating: "B", ratingPreviousMonth: "BB",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: true,
    recentNegativeEvents: ["Perda de contrato relevante com cliente principal"],
    stage: 2, pdPercent: 0.50, lgdPercent: 0.65,
    ead: 156000, ecl: 156000 * 0.50 * 0.65, pddRequired: 156000 * 0.50 * 0.65,
    sicr: true, sicrReasons: ["Atraso 61-90 dias", "Downgrade de rating"],
    earlyWarningScore: 68, earlyWarningSignals: ["Perda de contrato relevante", "Concentração de receita"],
  },
  {
    id: "PDD-004", name: "Eta Software", cnpj: "78.912.345/0001-04",
    segment: "small_business", totalExposure: 132000, daysOverdue: 50, oldestDueDate: "2025-01-18",
    internalRating: "BB", ratingPreviousMonth: "BBB",
    hasCollateral: false, collateralValue: 0, isRestructured: true, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 2, pdPercent: 0.20, lgdPercent: 0.50,
    ead: 132000, ecl: 132000 * 0.20 * 0.50, pddRequired: 132000 * 0.20 * 0.50,
    sicr: true, sicrReasons: ["Atraso 31-60 dias", "Reestruturação de dívida em andamento"],
    earlyWarningScore: 52, earlyWarningSignals: ["Solicitação de reestruturação", "Downgrade de rating"],
  },
  {
    id: "PDD-005", name: "Mu Analytics", cnpj: "23.456.789/0001-05",
    segment: "mid_market", totalExposure: 118000, daysOverdue: 43, oldestDueDate: "2025-01-25",
    internalRating: "BB", ratingPreviousMonth: "BBB",
    hasCollateral: true, collateralValue: 60000, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 2, pdPercent: 0.20, lgdPercent: 0.40, // reduced from 0.50 due to collateral
    ead: 118000, ecl: 118000 * 0.20 * 0.40, pddRequired: 118000 * 0.20 * 0.40,
    sicr: true, sicrReasons: ["Atraso 31-60 dias"],
    earlyWarningScore: 45, earlyWarningSignals: ["Atraso crescente nos pagamentos"],
  },
  {
    id: "PDD-006", name: "Rho Digital", cnpj: "56.789.123/0001-06",
    segment: "small_business", totalExposure: 95000, daysOverdue: 32, oldestDueDate: "2025-02-05",
    internalRating: "BBB", ratingPreviousMonth: "BBB",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 2, pdPercent: 0.20, lgdPercent: 0.50,
    ead: 95000, ecl: 95000 * 0.20 * 0.50, pddRequired: 95000 * 0.20 * 0.50,
    sicr: true, sicrReasons: ["Atraso 31-60 dias"],
    earlyWarningScore: 42, earlyWarningSignals: ["Primeiro atraso significativo"],
  },
  {
    id: "PDD-007", name: "Chi Data", cnpj: "89.123.456/0001-07",
    segment: "small_business", totalExposure: 82000, daysOverdue: 27, oldestDueDate: "2025-02-10",
    internalRating: "BBB", ratingPreviousMonth: "A",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 1, pdPercent: 0.03, lgdPercent: 0.35,
    ead: 82000, ecl: 82000 * 0.03 * 0.35, pddRequired: 82000 * 0.03 * 0.35,
    sicr: false, sicrReasons: [],
    earlyWarningScore: 28, earlyWarningSignals: ["Downgrade recente de rating"],
  },
  {
    id: "PDD-008", name: "Prism Digital", cnpj: "34.567.891/0001-08",
    segment: "small_business", totalExposure: 74000, daysOverdue: 22, oldestDueDate: "2025-02-15",
    internalRating: "A", ratingPreviousMonth: "A",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 1, pdPercent: 0.03, lgdPercent: 0.35,
    ead: 74000, ecl: 74000 * 0.03 * 0.35, pddRequired: 74000 * 0.03 * 0.35,
    sicr: false, sicrReasons: [],
    earlyWarningScore: 20, earlyWarningSignals: [],
  },
  {
    id: "PDD-009", name: "Helix Data", cnpj: "67.891.234/0001-09",
    segment: "mid_market", totalExposure: 68000, daysOverdue: 17, oldestDueDate: "2025-02-20",
    internalRating: "A", ratingPreviousMonth: "A",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 1, pdPercent: 0.03, lgdPercent: 0.35,
    ead: 68000, ecl: 68000 * 0.03 * 0.35, pddRequired: 68000 * 0.03 * 0.35,
    sicr: false, sicrReasons: [],
    earlyWarningScore: 15, earlyWarningSignals: [],
  },
  {
    id: "PDD-010", name: "Jade Software", cnpj: "91.234.567/0001-10",
    segment: "small_business", totalExposure: 72000, daysOverdue: 15, oldestDueDate: "2025-02-22",
    internalRating: "A", ratingPreviousMonth: "AA",
    hasCollateral: true, collateralValue: 45000, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 1, pdPercent: 0.03, lgdPercent: 0.20, // reduced from 0.35 due to collateral
    ead: 72000, ecl: 72000 * 0.03 * 0.20, pddRequired: 72000 * 0.03 * 0.20,
    sicr: false, sicrReasons: [],
    earlyWarningScore: 18, earlyWarningSignals: ["Downgrade leve de rating"],
  },
  {
    id: "PDD-011", name: "Nexus Holdings", cnpj: "11.222.333/0001-44",
    segment: "corporate", totalExposure: 520000, daysOverdue: 0, oldestDueDate: "2025-04-15",
    internalRating: "AAA", ratingPreviousMonth: "AAA",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: false,
    recentNegativeEvents: [],
    stage: 1, pdPercent: 0.01, lgdPercent: 0.30,
    ead: 520000, ecl: 520000 * 0.01 * 0.30, pddRequired: 520000 * 0.01 * 0.30,
    sicr: false, sicrReasons: [],
    earlyWarningScore: 8, earlyWarningSignals: [],
  },
  {
    id: "PDD-012", name: "Sigma Retail", cnpj: "55.666.777/0001-88",
    segment: "mid_market", totalExposure: 210000, daysOverdue: 45, oldestDueDate: "2025-01-23",
    internalRating: "BB", ratingPreviousMonth: "BBB",
    hasCollateral: false, collateralValue: 0, isRestructured: false, isOnWatchlist: true,
    recentNegativeEvents: ["Redução de quadro de funcionários em 30%", "Fechamento de 2 filiais"],
    stage: 2, pdPercent: 0.20, lgdPercent: 0.50,
    ead: 210000, ecl: 210000 * 0.20 * 0.50, pddRequired: 210000 * 0.20 * 0.50,
    sicr: true, sicrReasons: ["Atraso 31-60 dias", "Downgrade de rating", "Eventos negativos relevantes"],
    earlyWarningScore: 58, earlyWarningSignals: ["Redução de quadro", "Fechamento de filiais", "Watchlist ativa"],
  },
];

// ── Parameters ──

export const pddParameters: PddParameter[] = [
  {
    id: "PAR-001", bucketRange: "Corrente (0d)", stage: 1, pdPercent: 0.01, lgdPercent: 0.30,
    basis: "CPC48", lastUpdated: "2025-01-15", updatedBy: "Carlos Mendes — Controller",
    justification: "PD baseada em taxa de default histórica de clientes adimplentes (2020-2024). LGD conservadora de 30% conforme matriz de recuperação da carteira.",
  },
  {
    id: "PAR-002", bucketRange: "1-30 dias", stage: 1, pdPercent: 0.03, lgdPercent: 0.35,
    basis: "CPC48", lastUpdated: "2025-01-15", updatedBy: "Carlos Mendes — Controller",
    justification: "Aumento marginal de PD para atrasos iniciais. Histórico mostra 97% de recuperação nesta faixa. LGD ajustada para 35% incluindo custos de cobrança.",
  },
  {
    id: "PAR-003", bucketRange: "31-60 dias", stage: 2, pdPercent: 0.20, lgdPercent: 0.50,
    basis: "CPC48", lastUpdated: "2025-01-15", updatedBy: "Carlos Mendes — Controller",
    justification: "Migração para Stage 2 (SICR identificado). PD de 20% baseada em análise de cohort de clientes que ultrapassaram 30 dias nos últimos 5 anos. LGD 50% reflete deterioração significativa.",
  },
  {
    id: "PAR-004", bucketRange: "61-90 dias", stage: 2, pdPercent: 0.50, lgdPercent: 0.65,
    basis: "CPC48", lastUpdated: "2025-01-15", updatedBy: "Carlos Mendes — Controller",
    justification: "PD de 50% — metade dos créditos nesta faixa historicamente resultam em default. LGD 65% considera baixa taxa de recuperação sem garantias reais.",
  },
  {
    id: "PAR-005", bucketRange: "+90 dias", stage: 3, pdPercent: 1.00, lgdPercent: 0.80,
    basis: "CPC48", lastUpdated: "2025-01-15", updatedBy: "Carlos Mendes — Controller",
    justification: "Default presumido (PD 100%) conforme CPC 48.B5.5.37. LGD de 80% baseada em taxa de recuperação média de 20% da carteira em Stage 3 nos últimos 3 anos.",
  },
];

// ── Closing ──

const _totalEAD = pddDebtors.reduce((s, d) => s + d.ead, 0);
const _totalECL = pddDebtors.reduce((s, d) => s + d.ecl, 0);
const _stage1EAD = pddDebtors.filter(d => d.stage === 1).reduce((s, d) => s + d.ead, 0);
const _stage1ECL = pddDebtors.filter(d => d.stage === 1).reduce((s, d) => s + d.ecl, 0);
const _stage2EAD = pddDebtors.filter(d => d.stage === 2).reduce((s, d) => s + d.ead, 0);
const _stage2ECL = pddDebtors.filter(d => d.stage === 2).reduce((s, d) => s + d.ecl, 0);
const _stage3EAD = pddDebtors.filter(d => d.stage === 3).reduce((s, d) => s + d.ead, 0);
const _stage3ECL = pddDebtors.filter(d => d.stage === 3).reduce((s, d) => s + d.ecl, 0);
const _prevMonth = Math.round(_totalECL * 0.92);
const _constitution = _totalECL - _prevMonth;
const _reversal = 24500;
const _writeOff = 87000;
const _recovery = 18000;

export const currentClosing: PddClosing = {
  id: "CLO-202503",
  referenceMonth: "Mar/2025",
  closingDate: "2025-03-31",
  status: "pending_approval",
  approvedBy: null,
  totalEAD: _totalEAD,
  totalECL: _totalECL,
  totalPddBalance: _totalECL,
  totalPddPreviousMonth: _prevMonth,
  movementConstitution: _constitution,
  movementReversal: _reversal,
  movementWriteOff: _writeOff,
  movementRecovery: _recovery,
  netMovement: _constitution - _reversal - _writeOff + _recovery,
  journalEntryId: null,
  stage1EAD: _stage1EAD, stage1ECL: _stage1ECL,
  stage2EAD: _stage2EAD, stage2ECL: _stage2ECL,
  stage3EAD: _stage3EAD, stage3ECL: _stage3ECL,
  coverageRatio: _totalECL / _totalEAD,
  nplRatio: _stage3EAD / _totalEAD,
};

// ── History (12 months) ──

export const pddHistory: PddHistory[] = [
  { month: "Abr/24", referenceDate: "2024-04-30", totalEAD: 1680000, totalPdd: 142000, coverageRatio: 0.085, stage1Pdd: 18000, stage2Pdd: 48000, stage3Pdd: 76000, nplRatio: 0.068, costOfCredit: 0.085 * 12 },
  { month: "Mai/24", referenceDate: "2024-05-31", totalEAD: 1720000, totalPdd: 149000, coverageRatio: 0.087, stage1Pdd: 19000, stage2Pdd: 50000, stage3Pdd: 80000, nplRatio: 0.072, costOfCredit: 0.087 * 12 },
  { month: "Jun/24", referenceDate: "2024-06-30", totalEAD: 1755000, totalPdd: 158000, coverageRatio: 0.090, stage1Pdd: 19500, stage2Pdd: 54000, stage3Pdd: 84500, nplRatio: 0.075, costOfCredit: 0.090 * 12 },
  { month: "Jul/24", referenceDate: "2024-07-31", totalEAD: 1790000, totalPdd: 165000, coverageRatio: 0.092, stage1Pdd: 20000, stage2Pdd: 56000, stage3Pdd: 89000, nplRatio: 0.078, costOfCredit: 0.092 * 12 },
  { month: "Ago/24", referenceDate: "2024-08-31", totalEAD: 1830000, totalPdd: 174000, coverageRatio: 0.095, stage1Pdd: 20500, stage2Pdd: 60000, stage3Pdd: 93500, nplRatio: 0.082, costOfCredit: 0.095 * 12 },
  { month: "Set/24", referenceDate: "2024-09-30", totalEAD: 1870000, totalPdd: 183000, coverageRatio: 0.098, stage1Pdd: 21000, stage2Pdd: 63000, stage3Pdd: 99000, nplRatio: 0.085, costOfCredit: 0.098 * 12 },
  { month: "Out/24", referenceDate: "2024-10-31", totalEAD: 1910000, totalPdd: 194000, coverageRatio: 0.102, stage1Pdd: 21500, stage2Pdd: 67000, stage3Pdd: 105500, nplRatio: 0.090, costOfCredit: 0.102 * 12 },
  { month: "Nov/24", referenceDate: "2024-11-30", totalEAD: 1940000, totalPdd: 206000, coverageRatio: 0.106, stage1Pdd: 22000, stage2Pdd: 72000, stage3Pdd: 112000, nplRatio: 0.095, costOfCredit: 0.106 * 12 },
  { month: "Dez/24", referenceDate: "2024-12-31", totalEAD: 1980000, totalPdd: 218000, coverageRatio: 0.110, stage1Pdd: 22500, stage2Pdd: 76000, stage3Pdd: 119500, nplRatio: 0.100, costOfCredit: 0.110 * 12 },
  { month: "Jan/25", referenceDate: "2025-01-31", totalEAD: 2020000, totalPdd: 232000, coverageRatio: 0.115, stage1Pdd: 23000, stage2Pdd: 82000, stage3Pdd: 127000, nplRatio: 0.105, costOfCredit: 0.115 * 12 },
  { month: "Fev/25", referenceDate: "2025-02-28", totalEAD: 2060000, totalPdd: 248000, coverageRatio: 0.120, stage1Pdd: 23500, stage2Pdd: 88000, stage3Pdd: 136500, nplRatio: 0.110, costOfCredit: 0.120 * 12 },
  { month: "Mar/25", referenceDate: "2025-03-31", totalEAD: _totalEAD, totalPdd: _totalECL, coverageRatio: _totalECL / _totalEAD, stage1Pdd: _stage1ECL, stage2Pdd: _stage2ECL, stage3Pdd: _stage3ECL, nplRatio: _stage3EAD / _totalEAD, costOfCredit: (_totalECL / _totalEAD) * 12 },
];

// ── Journal Entries ──

export const pddJournalEntries: PddJournalEntry[] = [
  {
    id: "PDD-JE-001", date: "2025-01-31", referenceMonth: "Jan/2025", type: "constitution",
    description: "Constituição PDD mensal — Jan/2025",
    debitAccount: "6.1", debitAccountName: "Despesas Operacionais",
    creditAccount: "1.1.2.03", creditAccountName: "(-) Provisão Devedores Duvidosos",
    amount: 232000, status: "posted", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: "Carlos Mendes", closingId: "CLO-202501",
  },
  {
    id: "PDD-JE-002", date: "2025-02-28", referenceMonth: "Fev/2025", type: "constitution",
    description: "Constituição PDD mensal — Fev/2025",
    debitAccount: "6.1", debitAccountName: "Despesas Operacionais",
    creditAccount: "1.1.2.03", creditAccountName: "(-) Provisão Devedores Duvidosos",
    amount: 248000, status: "posted", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: "Carlos Mendes", closingId: "CLO-202502",
  },
  {
    id: "PDD-JE-003", date: "2025-03-31", referenceMonth: "Mar/2025", type: "constitution",
    description: "Constituição PDD mensal — Mar/2025",
    debitAccount: "6.1", debitAccountName: "Despesas Operacionais",
    creditAccount: "1.1.2.03", creditAccountName: "(-) Provisão Devedores Duvidosos",
    amount: _totalECL, status: "auto_generated", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: null, closingId: "CLO-202503",
  },
  {
    id: "PDD-JE-004", date: "2025-03-15", referenceMonth: "Mar/2025", type: "reversal",
    description: "Reversão PDD — Cliente Chi Data regularizou pagamento",
    debitAccount: "1.1.2.03", debitAccountName: "(-) Provisão Devedores Duvidosos",
    creditAccount: "6.1", creditAccountName: "Despesas Operacionais",
    amount: 24500, status: "auto_generated", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: null, closingId: "CLO-202503",
  },
  {
    id: "PDD-JE-005", date: "2025-03-20", referenceMonth: "Mar/2025", type: "write_off",
    description: "Baixa por perda — Devedor irrecuperável (processo encerrado)",
    debitAccount: "1.1.2.03", debitAccountName: "(-) Provisão Devedores Duvidosos",
    creditAccount: "1.1.2.01", creditAccountName: "Clientes Nacionais",
    amount: 87000, status: "auto_generated", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: null, closingId: "CLO-202503",
  },
  {
    id: "PDD-JE-006", date: "2025-03-22", referenceMonth: "Mar/2025", type: "recovery",
    description: "Recuperação de crédito baixado — Pagamento parcial recebido",
    debitAccount: "1.1.1.02", debitAccountName: "Banco Itaú CC 32.12345-6",
    creditAccount: "6.1", creditAccountName: "Despesas Operacionais",
    amount: 18000, status: "auto_generated", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: null, closingId: "CLO-202503",
  },
  {
    id: "PDD-JE-007", date: "2025-01-15", referenceMonth: "Jan/2025", type: "recovery",
    description: "Recuperação de crédito — Cliente antigo quitou parcialmente",
    debitAccount: "1.1.1.02", debitAccountName: "Banco Itaú CC 32.12345-6",
    creditAccount: "6.1", creditAccountName: "Despesas Operacionais",
    amount: 12000, status: "posted", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: "Carlos Mendes", closingId: "CLO-202501",
  },
  {
    id: "PDD-JE-008", date: "2025-02-10", referenceMonth: "Fev/2025", type: "write_off",
    description: "Baixa por perda — Devedor com falência decretada",
    debitAccount: "1.1.2.03", debitAccountName: "(-) Provisão Devedores Duvidosos",
    creditAccount: "1.1.2.01", creditAccountName: "Clientes Nacionais",
    amount: 65000, status: "posted", autoGenerated: true,
    generatedBy: "Motor PDD — FinanceOS", approvedBy: "Carlos Mendes", closingId: "CLO-202502",
  },
];

// ── Overrides ──

export const pddOverrides: PddOverride[] = [
  {
    id: "OVR-001", debtorId: "PDD-001", debtorName: "Omega Corp",
    field: "lgdPercent", originalValue: 0.80, overrideValue: 0.65,
    justification: "Garantia real registrada em cartório avaliada em R$ 180.000. Aprovado pelo Comitê de Crédito em 10/03/2025.",
    requestedBy: "Ana Lima — Analista de Crédito", approvedBy: "Carlos Mendes — Controller",
    date: "2025-03-10", status: "approved",
  },
  {
    id: "OVR-002", debtorId: "PDD-004", debtorName: "Eta Software",
    field: "stage", originalValue: 2, overrideValue: 1,
    justification: "Cliente reestruturou dívida com novo calendário de pagamentos (6 parcelas). Primeira parcela já quitada. Aguarda aprovação gerencial.",
    requestedBy: "Rafael Costa — Gestor Financeiro", approvedBy: null,
    date: "2025-03-12", status: "pending",
  },
  {
    id: "OVR-003", debtorId: "PDD-003", debtorName: "Kappa Serviços",
    field: "pdPercent", originalValue: 0.50, overrideValue: 0.20,
    justification: "Solicitação de redução de PD baseada em expectativa de pagamento. Rejeitada: redução não suportada por evidências objetivas de melhora na capacidade de pagamento.",
    requestedBy: "Mariana Alves — Comercial", approvedBy: "Carlos Mendes — Controller",
    date: "2025-03-08", status: "rejected",
  },
];

// ── Macro Scenarios ──

export const macroScenarios: MacroScenario[] = [
  {
    id: "base", name: "Cenário Base", probability: 60,
    gdpGrowth: 2.0, interestRate: 10.5, unemployment: 7.8, inflation: 4.2,
    pdMultiplier: 1.0, lgdMultiplier: 1.0,
    expectedPddImpact: 0, // will be recalculated below
    color: "hsl(217,91%,60%)",
  },
  {
    id: "optimistic", name: "Cenário Otimista", probability: 25,
    gdpGrowth: 3.5, interestRate: 9.0, unemployment: 6.5, inflation: 3.5,
    pdMultiplier: 0.80, lgdMultiplier: 0.85,
    expectedPddImpact: 0,
    color: "hsl(142,76%,36%)",
  },
  {
    id: "pessimistic", name: "Cenário Pessimista", probability: 15,
    gdpGrowth: -0.5, interestRate: 13.5, unemployment: 9.5, inflation: 6.8,
    pdMultiplier: 1.40, lgdMultiplier: 1.25,
    expectedPddImpact: 0,
    color: "hsl(354,100%,64%)",
  },
];

// Recalculate expectedPddImpact
macroScenarios.forEach(sc => {
  sc.expectedPddImpact = _totalECL * sc.pdMultiplier * sc.lgdMultiplier - _totalECL;
});

// ── Exported Aggregates ──

export const totalEAD = _totalEAD;
export const totalECL = _totalECL;
export const totalPddBalance = _totalECL;
export const coverageRatio = _totalECL / _totalEAD;
export const nplRatio = _stage3EAD / _totalEAD;
export const weightedECL = macroScenarios.reduce(
  (s, sc) => s + (sc.probability / 100) * _totalECL * sc.pdMultiplier * sc.lgdMultiplier, 0
);
